function l(b,a,c,d,e){b.s.jb(b.ob,a,c,d,e)}function m(b,a,c,d){b.s.ca?l(b,a,c,d):b.s.Ie()._OnMessageFromDOM({type:"event",component:b.ob,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.s.C(b.ob,a,c)}function aa(b,a){for(const [c,d]of a)q(b,c,d)}function t(b){b.Ub||(b.s.td(b.ae),b.Ub=!0)}function ba(b){b.Ub&&(b.s.Ve(b.ae),b.Ub=!1)}window.Hb=class{constructor(b,a){this.s=b;this.ob=a;this.Ub=!1;this.ae=()=>this.Da()}kd(){}Da(){}};
window.tf=class{constructor(){this.fd=-1}j(){-1!==this.fd&&(self.clearTimeout(this.fd),this.fd=-1)}};"use strict";class ca{constructor(b){this.Sb=b;this.Pc=!1;this.Xc=!0}}function da(b,a){const c=a.elementId,d=b.qc(c,a),e=new ca(d);b.Pa.set(c,e);d.style.boxSizing="border-box";d.style.display="none";e.Xc=!!a.isVisible;d.addEventListener("focus",()=>{u(b,"elem-focused",c)});d.addEventListener("blur",()=>{u(b,"elem-blurred",c)});b.mb&&document.body.appendChild(d)}
function v(b,a,c){q(b,a,d=>{const e=w(b,d.elementId);return c(e,d)})}function w(b,a){b=b.Pa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Sb}function u(b,a,c,d){d||(d={});d.elementId=c;l(b,a,d)}function ea(b,a,c){var d;d||(d={});d.elementId=c;m(b,a,d)}
window.od=class extends self.Hb{constructor(b,a){super(b,a);this.Pa=new Map;this.mb=!0;aa(this,[["create",c=>da(this,c)],["destroy",c=>{c=c.elementId;const d=w(this,c);this.qd(d);this.mb&&d.parentElement.removeChild(d);this.Pa.delete(c)}],["set-visible",c=>{if(this.mb){var d=this.Pa.get(c.elementId),e=d.Sb;d.Pc?e.style.display=c.isVisible?"":"none":d.Xc=!!c.isVisible}}],["update-position",c=>{if(this.mb){var d=this.Pa.get(c.elementId),e=d.Sb;e.style.left=c.left+"px";e.style.top=c.top+"px";e.style.width=
c.width+"px";e.style.height=c.height+"px";c=c.fontSize;null!==c&&(e.style.fontSize=c+"em");d.Pc||(d.Pc=!0,d.Xc&&(e.style.display=""))}}],["update-state",c=>{const d=w(this,c.elementId);this.Lb(d,c)}],["focus",c=>{const d=w(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=w(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{w(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{w(this,c.elementId).removeAttribute(c.name)}]]);
v(this,"get-element",c=>c)}qc(){throw Error("required override");}qd(){}Lb(){throw Error("required override");}};"use strict";const fa=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),ha=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ia=0;
function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.hf?new Promise(c=>{const d="c3_resolve_"+ia;++ia;self[d]=c;a.textContent=b.mf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ja=!1,ka=!1;function la(){if(!ja){try{new Worker("blob://",{get type(){ka=!0}})}catch(b){}ja=!0}return ka}let A=new Audio;
const ma={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function na(b){b=await qa(b);return(new TextDecoder("utf-8")).decode(b)}
function qa(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const ra=[];let B=0;window.RealFile=window.File;const C=[],sa=new Map,ta=new Map;let ua=0;const va=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");va.push(b)};const wa=new Set(["cordova","playable-ad","instant-games"]);let xa=!1;
window.La=class b{constructor(a){this.ca=a.pf;this.ya=null;this.ba="";this.Za=a.lf;this.Fb={};this.Sa=this.wa=null;this.Rb=[];this.J=this.pa=null;this.Tc=!1;this.Id=0;this.tb=null;this.Ya=-1;this.cf=()=>this.Qe();this.Xa=[];this.gd=null;this.be=[];this.A=a.ce;this.Vb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&la()||(this.ca=!1);this.ca&&ha&&(this.ca=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ca=!1;if("cordova"===
this.A&&this.ca)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&90<=parseInt(c[1],10)||(this.ca=!1)}else this.ca=!1;this.hb()?self.chrome.webview.addEventListener("message",c=>this.yd(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.yd(c));this.Yb=this.ta=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");
this.C("runtime","cordova-fetch-local-file",c=>this.Me(c));this.C("runtime","create-job-worker",()=>this.Ne());this.C("runtime","send-wrapper-extension-message",c=>this.Te(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.wd(a)):this.wd(a)}j(){this.Bc();this.ya&&(this.ya=this.ya.onmessage=null);this.wa&&(this.wa.terminate(),this.wa=null);this.Sa&&(this.Sa.j(),this.Sa=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}xe(){return fa&&"cordova"===this.A}xc(){const a=
navigator.userAgent;return fa&&wa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ve(){return x}wc(){return x&&wa.has(this.A)}hb(){return"windows-webview2"===this.A||!!("preview"===this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}async wd(a){"macos-wkwebview"===this.A?this.kb({type:"ready"}):this.hb()&&(this.We(),this.be=(await this.Le()).registeredComponentIds);if("playable-ad"===this.A){this.ta=self.c3_base64files;this.Yb={};await this.Ee();
for(let d=0,e=a.ab.length;d<e;++d){var c=a.ab[d];this.Yb.hasOwnProperty(c)?a.ab[d]={hf:!0,mf:this.Yb[c]}:this.ta.hasOwnProperty(c)&&(a.ab[d]=URL.createObjectURL(this.ta[c]))}a.oc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.td(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.kf?this.ba=a.kf:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.rf&&(this.Fb=a.rf);
c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Pe(d));this.tb=new self.ye(this);await ya(this.tb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ca?await this.Ke(a,c.port2):
await this.Je(a,c.port2)}Dc(a){a=this.Fb.hasOwnProperty(a)?this.Fb[a]:a.endsWith("/workermain.js")&&this.Fb.hasOwnProperty("workermain.js")?this.Fb["workermain.js"]:"playable-ad"===this.A&&this.ta.hasOwnProperty(a)?this.ta[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Vb)return a=await this.Gb(d.gf?a:this.Za+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=
new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ka(){return Math.max(window.innerHeight,1)}vd(a){var c=this.ba,d=location.href,e=this.ra(),f=this.ka(),g=window.devicePixelRatio,h=b.gb(),k=a.wf,n=window.cr_previewImageBlobs||this.ta,p=window.cr_previewProjectFileBlobs,D=window.cr_previewProjectFiles,z=window.cr_swClientId||
"";a=a.ce;var r=(new URLSearchParams(self.location.search)).has("debug"),E=this.tb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:n,previewProjectFileBlobs:p,previewProjectFileSWUrls:D,swClientId:z,exportType:a,isDebug:r,ife:!!self.vf,jobScheduler:{inputPort:E.Sc,outputPort:E.ad,maxNumWorkers:E.$e},supportedAudioFormats:ma,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Za+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Za+"opus.wasm.wasm",isFileProtocol:this.Vb,isiOSCordova:this.xe(),isiOSWebView:this.xc(),isWebView2Wrapper:this.hb(),wrapperComponentIds:this.be,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ke(a,c){const d=this.Dc(a.qf);"preview"===this.A?(this.wa=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const n=p=>{this.wa.removeEventListener("message",n);p.data&&"ok"===p.data.type?h():k()};this.wa.addEventListener("message",n);this.wa.postMessage({type:"construct-worker-init",
"import":(new URL(d,this.ba)).toString()})})):this.wa=await this.rc(d,this.ba,{type:"module",name:"Runtime",gf:!0});this.J=document.createElement("canvas");this.J.style.display="none";const e=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.oc||[],g=a.ab;f=await Promise.all(f.map(h=>this.Ma(h)));g=await Promise.all(g.map(h=>this.Ma(h)));if("cordova"===this.A)for(let h=0,k=a.nc.length;h<
k;++h){const n=a.nc[h],p=n[0];if(p===a.hd||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n[1]=await this.Ma(p)}this.wa.postMessage(Object.assign(this.vd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.nc,mainProjectScript:a.hd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,e,...za(this.tb)]);this.Rb=C.map(h=>new h(this));this.ud();Aa(this.pa);self.c3_callFunction=(h,k)=>{var n=this.pa;return n.s.sd(n.ob,
"js-invoke-function",{name:h,params:k})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.jb("runtime","go-to-last-error-script"))}async Je(a,c){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Rb=C.map(g=>new g(this));this.ud();var d=a.ab.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);if(Array.isArray(a.oc)){var e=[...a.oc].map(g=>
g instanceof Blob?URL.createObjectURL(g):g);d.unshift(...e)}d=await Promise.all(d.map(g=>this.Ma(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;e=a.hd;const f=a.nc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ma(h),await y(h),"preview"!==this.A||d[g]||this.zd(g,"main script did not run to completion")}catch(k){this.zd(g,k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ma(h),await y(h);"preview"===this.A&&"object"!==typeof self.sf.uf?
(this.Nb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.vd(a),{isInWorker:!1,messagePort:c,canvas:this.J,runOnStartupFunctions:va}),Aa(this.pa),this.xd(),this.Sa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Sa,a))}zd(a,c){this.Nb();console.error(`[Preview] Failed to load project main script (${a}): `,
c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}xd(){this.Nb()}Nb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ne(){const a=await Ba(this.tb);return{outputPort:a,transferables:[a]}}Ie(){if(this.ca)throw Error("not available in worker mode");return this.Sa}jb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,
dispatchOpts:e||null,data:d,responseId:null},f)}sd(a,c,d,e,f){const g=ua++,h=new Promise((k,n)=>{ta.set(g,{resolve:k,reject:n})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Oe(a);if("result"===c)this.Re(a);else if("runtime-ready"===c)this.Se();else if("alert-error"===c)this.Nb(),alert(a.message);else if("creating-runtime"===c)this.xd();else throw Error(`unknown message '${c}'`);
}Oe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=sa.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Mb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Mb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Mb(f,!1,""+h)}):this.Mb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Mb(a,
c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Re(a){const c=a.responseId,d=a.isOk;a=a.result;const e=ta.get(c);d?e.resolve(a):e.reject(a);ta.delete(c)}C(a,c,d){let e=sa.get(a);e||(e=new Map,sa.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static bb(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}ud(){for(const a of this.Rb)if("runtime"===a.ob){this.pa=
a;return}throw Error("cannot find runtime DOM handler");}Pe(a){this.jb("debugger","message",a)}Se(){for(const a of this.Rb)a.kd()}static gb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||xa)}static Ad(a){xa=!!a}td(a){this.Xa.push(a);this.Ic()}Ve(a){a=this.Xa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Xa.splice(a,1);this.Xa.length||this.Bc()}Ic(){-1===this.Ya&&this.Xa.length&&(this.Ya=requestAnimationFrame(this.cf))}Bc(){-1!==
this.Ya&&(cancelAnimationFrame(this.Ya),this.Ya=-1)}Qe(){this.Ya=-1;for(const a of this.Xa)a();this.Ic()}ea(a){this.pa.ea(a)}ja(a){this.pa.ja(a)}Hc(){this.pa.Hc()}Kb(a){this.pa.Kb(a)}we(){return!!ma["audio/webm; codecs=opus"]}async Xe(a){a=await this.sd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ae(a){this.Tc=!0;this.Id=a}ue(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}rd(a){return!this.ue(a)}async Ma(a){return"cordova"===
this.A&&(a.startsWith("file:")||this.Vb&&this.rd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Gb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Me(a){const c=a.filename;switch(a.as){case "text":return await this.te(c);case "buffer":return await this.Gb(c);default:throw Error("unsupported type");}}nd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async te(a){a=
await this.nd(a);return await na(a)}Cc(){if(ra.length&&!(8<=B)){B++;var a=ra.shift();this.Fe(a.filename,a.nf,a.ff)}}Gb(a){return new Promise((c,d)=>{ra.push({filename:a,nf:e=>{B--;this.Cc();c(e)},ff:e=>{B--;this.Cc();d(e)}});this.Cc()})}async Fe(a,c,d){try{const e=await this.nd(a),f=await qa(e);c(f)}catch(e){d(e)}}yd(a){if("entered-fullscreen"===a)b.Ad(!0),F(this.pa);else if("exited-fullscreen"===a)b.Ad(!1),F(this.pa);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.gd(a),
this.gd=null):"extension-message"===c?this.jb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Te(a){this.kb({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}kb(a){this.hb()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}We(){window.moveTo=(a,c)=>
{this.kb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.kb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Le(){return this.hb()?new Promise(a=>{this.gd=a;this.kb({type:"wrapper-init"})}):Promise.resolve()}async Ee(){const a=[];for(const [c,d]of Object.entries(this.ta))a.push(this.De(c,d));await Promise.all(a)}async De(a,c){if("object"===typeof c)this.ta[a]=new Blob([c.str],{type:c.type}),this.Yb[a]=c.str;else{let d=
await this.He(c);d||(d=this.Ge(c));this.ta[a]=d}}async He(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Ge(a){a=this.Ue(a);return this.Ce(a.data,a.jf)}Ue(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,
c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{jf:a,data:d}}Ce(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const H=self.La;
function Ca(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const Da=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Ea={dispatchUserScriptEvent:!0},Fa={dispatchRuntimeEvent:!0};
function Ga(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function Ha(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await Ha(b)}finally{URL.revokeObjectURL(b)}}
function Ia(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ja(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Ia(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ka(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ma=new Set(["input","textarea","datalist","select"]),Na=new Set(["canvas","body","html"]);function K(b){b.target.tagName&&Na.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Oa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ja(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Pa=!1;document.addEventListener("pause",()=>Pa=!0);document.addEventListener("resume",()=>Pa=!1);function Aa(b){b.Hd=!0;b.Yc=b.s.ra();b.ub=b.s.ka()}function F(b){if(!b.$){var a=H.gb();a&&"any"!==b.dd&&Qa(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ka()})}}async function Ra(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Sa(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ta(b){return await self.C3_GetSvgImageSize(b.blob)}function Ua(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Va(b){self.setTimeout(()=>{b.Gd=!0},1E3);"cordova"===b.s.A?(document.addEventListener("pause",()=>Wa(b,!0)),document.addEventListener("resume",()=>Wa(b,!1))):document.addEventListener("visibilitychange",()=>Wa(b,"hidden"===document.visibilityState));b.cc=!("hidden"!==document.visibilityState&&!Pa);return{isSuspended:b.cc}}
function Xa(b){b.Cd||(b.Cd=!0,window.addEventListener("deviceorientation",a=>{b.$||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.$||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Ya(b){b.Bd||(b.Bd=!0,window.addEventListener("devicemotion",a=>{if(!b.$){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Za(b){await Ga(b.url)}
function $a(b,a){b.Jd=a.message;-1===b.Nc&&(b.Nc=setTimeout(()=>{b.Nc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Jd)},250))}function ab(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:H.gb(),innerWidth:b.ra(),innerHeight:b.ka()})}function Wa(b,a){b.cc!==a&&((b.cc=a)?b.s.Bc():b.s.Ic(),l(b,"visibilitychange",{hidden:a}))}
function bb(b,a,c){"Backspace"===c.key&&K(c);if(!b.$){var d=Da.get(c.code)||c.code;m(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}function db(b,a,c,d){b.$||Ca(c)||m(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function eb(b){window!==window.top&&window.focus();fb(b.target)&&document.activeElement&&!fb(document.activeElement)&&document.activeElement.blur()}
function L(b,a,c){if(!b.$){var d=0;"mouse"===c.pointerType&&(d=b.zb);m(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},I);"mouse"===c.pointerType&&(d=
"mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),db(b,d,c,Ea),b.zb=c.buttons)}}
function gb(b,a,c){if(!b.$&&!Ca(c)){var d=b.zb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");m(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.da,pageX:c.pageX,pageY:c.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.zb=c.buttons;db(b,c.type,c,Ea)}}
function M(b,a,c){if(!b.$)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];m(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.da,pageX:f.pageX,pageY:f.pageY+b.da,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function hb(b,a,c){document.body.style.transform="";b.da=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.da=a))}}function ib(b,a,c,d){const e=b.ra(),f=b.ka();b.$a=-1;e!=a||f!=c?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.gb()}):10>d&&jb(b,e,f,d+1)}
function jb(b,a,c,d){-1!==b.$a&&clearTimeout(b.$a);b.$a=setTimeout(()=>ib(b,a,c,d),48)}
function Qa(b){b=b.dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function fb(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.bb(class extends self.Hb{constructor(b){super(b,"runtime");this.Od=!0;this.Hd=!1;this.$a=-1;this.dd="any";this.cc=this.Bd=this.Cd=!1;this.jc=document.createElement("div");this.jc.className="c3-screen-reader-text";this.jc.setAttribute("aria-live","polite");document.body.appendChild(this.jc);this.Ga=null;this.$=!1;this.Jd="";this.Nc=-1;this.Gd=!1;this.Yc=b.ra();this.ub=b.ka();this.da=this.Eb=0;b.C("canvas","update-size",d=>{var e=this.s;e.Tc||(e=e.J,e.style.width=d.styleWidth+"px",e.style.height=
d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",d.displayScale),this.Od&&(e.style.display="",this.Od=!1))});b.C("runtime","invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","load-webfonts",d=>Ra(d));b.C("runtime","raster-svg-image",d=>Sa(d));b.C("runtime",
"get-svg-image-size",d=>Ta(d));b.C("runtime","set-target-orientation",d=>{this.dd=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ua(d));b.C("runtime","go-to-script",d=>Ua(d));b.C("runtime","before-start-ticking",()=>Va(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var e=this.Ga;e.style.display=
"";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ga&&(this.Ga.style.display="none")});b.C("runtime","enable-device-orientation",()=>Xa(this));b.C("runtime","enable-device-motion",()=>Ya(this));b.C("runtime","add-stylesheet",d=>Za(d));b.C("runtime","script-create-worker",d=>{const e=d.port2;(new Worker(d.url,d.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.C("runtime","alert",d=>{alert(d.message)});
b.C("runtime","screen-reader-text",d=>{var e=d.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+d.id,e.textContent=d.text,this.jc.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+d.id))?e.textContent=d.text:console.warn(`[Construct] Missing screen reader text with id ${d.id}`):"release"===e?(e=document.getElementById("c3-sr-"+d.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${d.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.$=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.J.style.display="";this.s.Ae(d.duration)});b.C("runtime","export-to-video-progress",d=>$a(this,d));b.C("runtime","exported-to-video",d=>{window.ef({type:"exported-video",
arrayBuffer:d.arrayBuffer,contentType:d.contentType,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.ef({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ka(e)||d.preventDefault()});const c=b.J;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",
K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.zb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Oa,{passive:!1});window.addEventListener("wheel",Oa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.$&&this.Hd){var d=this.ra();var e=this.ka();if(this.s.wc()){if(this.Gd){if(this.Yc===
d&&e<this.ub){this.Eb=this.ub-e;hb(this,this.ub,this.Eb);d=void 0;break a}0<this.Eb&&(this.Eb=0,hb(this,e,this.Eb))}this.Yc=d;this.ub=e}l(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.gb()});this.s.xc()&&(-1!==this.$a&&clearTimeout(this.$a),ib(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>F(this));window.addEventListener("webkitfullscreenchange",()=>F(this));window.addEventListener("mozfullscreenchange",()=>
F(this));window.addEventListener("fullscreenerror",d=>ab(this,d));window.addEventListener("webkitfullscreenerror",d=>ab(this,d));window.addEventListener("mozfullscreenerror",d=>ab(this,d));if(b.xc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ka(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.Ta=new Set;this.$b=new WeakSet;this.xa=!1}kd(){window.addEventListener("focus",()=>{l(this,"window-focus",null,Fa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}l(this,"window-blur",{parentHasFocus:a},Fa);this.zb=0});window.addEventListener("focusin",a=>{a=a.target;(Ma.has(a.tagName.toLowerCase())||Ka(a))&&
l(this,"keyboard-blur",null,Fa)});window.addEventListener("keydown",a=>bb(this,"keydown",a));window.addEventListener("keyup",a=>bb(this,"keyup",a));window.addEventListener("dblclick",a=>db(this,"dblclick",a,I));window.addEventListener("wheel",a=>{this.$||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.da,pageX:a.pageX,pageY:a.pageY+this.da,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
a=>{eb(a);L(this,"pointerdown",a)}),this.s.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{L(this,"pointermove",a)}):window.addEventListener("pointermove",a=>L(this,"pointermove",a)),window.addEventListener("pointerup",a=>L(this,"pointerup",a)),window.addEventListener("pointercancel",a=>L(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{eb(a);gb(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>gb(this,
"pointermove",a)),window.addEventListener("mouseup",a=>gb(this,"pointerup",a)),window.addEventListener("touchstart",a=>{eb(a);M(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>M(this,"pointermove",a)),window.addEventListener("touchend",a=>M(this,"pointerup",a)),window.addEventListener("touchcancel",a=>M(this,"pointercancel",a)));const b=()=>this.Hc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",
b,!0);window.addEventListener("gamepadconnected",b,!0);this.s.ve()&&!this.s.wc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{hb(this,this.ka(),navigator.virtualKeyboard.boundingRect.height)}))}ra(){return this.s.ra()}ka(){return this.s.ka()}Hc(){var b=[...this.Ta];this.Ta.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.$b.has(a)||this.Ta.add(a)})}ea(b){if("function"!==typeof b.play)throw Error("missing play function");
this.$b.delete(b);let a;try{a=b.play()}catch(c){this.Ta.add(b);return}a&&a.catch(()=>{this.$b.has(b)||this.Ta.add(b)})}ja(b){this.Ta.delete(b);this.$b.add(b)}Kb(b){this.xa=!!b}});"use strict";async function ya(b){if(b.Ye)throw Error("already initialised");b.Ye=!0;var a=b.za.Dc(("playable-ad"===b.za.A?b.za.Za:"")+"dispatchworker.js");b.Mc=await b.za.rc(a,b.nb,{name:"DispatchWorker"});a=new MessageChannel;b.Sc=a.port1;b.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.ad=await Ba(b)}
function za(b){return[b.Sc,b.ad]}async function Ba(b){const a=b.Pd.length;var c=b.za.Dc(("playable-ad"===b.za.A?b.za.Za:"")+"jobworker.js");c=await b.za.rc(c,b.nb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Pd.push(c);return e.port1}
self.ye=class{constructor(b){this.za=b;this.nb=b.ba;this.nb="preview"===b.A?this.nb+"workers/":this.nb+b.Za;this.$e=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Pd=[];this.ad=this.Sc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.La({pf:!0,qf:"workermain.js",ab:["scripts/c3runtime.js"],nc:[],hd:"",lf:"scripts/",oc:[],ce:"html5"}));"use strict";function N(b){b.stopPropagation()}function kb(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.La.bb(class extends self.od{constructor(b){super(b,"text-input");v(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}qc(b,a){let c;const d=a.type;"textarea"===d?(c=document.createElement("textarea"),c.style.resize="none"):(c=document.createElement("input"),c.type=d);c.style.position="absolute";c.autocomplete="off";c.addEventListener("pointerdown",N);c.addEventListener("pointermove",N);c.addEventListener("pointerrawupdate",N);c.addEventListener("pointerup",N);c.addEventListener("mousedown",
N);c.addEventListener("mouseup",N);c.addEventListener("keydown",kb);c.addEventListener("keyup",kb);c.addEventListener("click",e=>{e.stopPropagation();ea(this,"click",b)});c.addEventListener("dblclick",e=>{e.stopPropagation();ea(this,"dblclick",b)});c.addEventListener("input",()=>u(this,"change",b,{text:c.value}));a.id&&(c.id=a.id);a.className&&(c.className=a.className);this.Lb(c,a);return c}Lb(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";async function lb(b,a){a=a.type;let c=!0;0===a?c=await mb():1===a&&(c=await nb());l(b,"permission-result",{type:a,result:c})}
async function mb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function nb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.La.bb(class extends self.Hb{constructor(b){super(b,"touch");q(this,"request-permission",a=>lb(this,a))}});"use strict";const ob=180/Math.PI;
async function pb(b,a){if(a.isiOSCordova||a.isSafari)b.ec=!0;b.ed=a.timeScaleMode;b.Ud=["equalpower","HRTF","soundfield"][a.panningModel];b.Fd=["linear","inverse","exponential"][a.distanceModel];b.Vd=a.refDistance;b.Td=a.maxDistance;b.Xd=a.rolloffFactor;if(b.s.Tc)b.ec=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.s.Id)});else{var c={latencyHint:a.latencyHint};b.$d||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");qb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&qb(b);l(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Oa=b.g.createGain();b.Oa.connect(b.g.destination);c=a.listenerPos;b.aa[0]=c[0];b.aa[1]=c[1];b.aa[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.fa);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>
O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function rb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,n=a.pos,p=a.panning,D=a.stereoPan;let z=a.off;0<z&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),z=z-a.performanceTime/1E3+a.contextTime):z=z-performance.now()/1E3+b.g.currentTime);b.Qd=g.slice(0);sb(b,g);try{b.R=await tb(b,c,d,e,g,f);if(p){P(b.R,!0);var r=b.R,E=p.innerAngle,oa=p.outerAngle,pa=p.outerGain;if(r.sb){ub(r,p.x,p.y,p.z,p.angle);var G=self.cb.Be;r.ua[0]!==G(E)&&
(r.ua[0]=G(E),r.F.coneInnerAngle=G(E));r.ua[1]!==G(oa)&&(r.ua[1]=G(oa),r.F.coneOuterAngle=G(oa));r.ua[2]!==pa&&(r.ua[2]=pa,r.F.coneOuterGain=pa)}p.hasOwnProperty("uid")&&(b.R.sa=p.uid)}else"number"===typeof D&&0!==D?(Q(b.R,!0),vb(b.R,D)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,n,z)}catch(Jb){console.error("[Construct] Audio: error starting playback: ",Jb);return}finally{c=g.join(" ");d=b.Bb.get(c);if(!d)throw Error("expected pending tag");d.jd--;0===d.jd&&(d.resolve(),b.Bb.delete(c))}t(b)}
async function wb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await xb(b,c);for(const h of R(b,c))if(!h.Ra){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ja=d;h.Qa=g;h.Zd=a}S(b)}async function yb(b,a){const c=a.tags;a=a.rate;await xb(b,c);for(const d of R(b,c))d.oa!==a&&(d.oa=a,d.Ea())}async function zb(b,a){const c=a.tags;a=a.pos;await xb(b,c);for(const d of R(b,c))d.yc(a)}
async function Ab(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await tb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function Bb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ma.indexOf(a),-1!==a&&b.ma.splice(a,1)}
async function Cb(b,a){const c=a.type;var d=a.tags;const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ie(b,...e);else if("delay"===c)d=new self.ge(b,...e);else if("convolution"===c){var g=d=new self.fe(b,f.la,...e),h=a.bufferType;g.Dd=a.bufferOriginalUrl;g.Ed=h}else if("flanger"===c)d=new self.je(b,...e);else if("phaser"===
c)d=new self.le(b,...e);else if("gain"===c)d=new self.ke(b,...e);else if("stereopan"===c)d=new self.ne(b,...e);else if("tremolo"===c)d=new self.oe(b,...e);else if("ringmod"===c)d=new self.me(b,...e);else if("distortion"===c)d=new self.he(b,...e);else if("compressor"===c)d=new self.ee(b,...e);else if("analyser"===c)d=new self.de(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let n=g.na.get(h);n||(n=[],g.na.set(h,n));d.Nd=n.length;d.cd=h;n.push(d);Db(g,h)}Eb(b)}
async function Fb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.na.values())for(const g of f)g.j();b.na.clear();b.lc=a.timeScale;b.Oc=a.gameTime;d=a.listenerPos;b.aa[0]=d[0];b.aa[1]=d[1];b.aa[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.fa[e]=d[e];b.g.listener.setOrientation(...b.fa)}b.xa=a.isSilent;b.s.Kb(b.xa);b.Zb=a.masterVolume;b.Oa.gain.value=
b.Zb;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>Cb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>Gb(b,f,c)));S(b)}
async function Ib(b,a){try{const c=b.g.suspend(a.time);b.Md?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.s.jb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Kb(d)),b.Md=!0);await c}catch(c){Kb(c)}}
function qb(b){b.Tb||(b.Rc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Tb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ma)if(g.fb()===c)return await Lb(g),g;if(f)return null;if(e&&(b.ec||b.Ld)){f=0;for(let h=0,k=b.ma.length;h<k;++h)g=b.ma[h],b.ma[f]=g,g.Ba()?g.j():++f;b.ma.length=f}f="audio/webm; codecs=opus"===d&&!b.$d;e&&f&&(b.Ld=!0);c=!e||b.ec||f?new self.re(b,a,c,d,e,f):new self.pe(b,a,c,d,e);b.ma.push(c);await Lb(c);b.Sd.has(a)||(l(b,"buffer-metadata",{originalUrl:a,duration:c.ia()}),b.Sd.add(a));return c}
function Mb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Nb(b,a){return(a=b.na.get(a.toLowerCase()))?a[0].N():b.ha()}function Db(b,a){a=a.toLowerCase();let c=b.ha();var d=b.na.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ha()):e.U(d[f+1].N())}}for(const f of Ob(b,a))d=c,e=f.ga||f.F||f.G,e.disconnect(),e.connect(d);b.Ha&&b.Zc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*Ob(b,a){if(a)for(const c of b.H)Mb(0<c.qa.length?c.qa[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Pb(b,a,c){return c?b.s.Xe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Qb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.qa;var c=a;for(const e of c){c=!1;for(const f of b)if(Mb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function tb(b,a,c,d,e,f){for(const g of b.H)if(g.fb()===c&&(g.pc()||f))return g.qa=e,g;a=await O(b,a,c,d,f);e="html5"===a.Jc?new self.qe(a.u,a,e):new self.se(a.u,a,e);b.H.push(e);return e}
function sb(b,a){a=a.join(" ");let c=b.Bb.get(a);if(!c){let d=null;c={jd:0,promise:new Promise(e=>d=e),resolve:d};b.Bb.set(a,c)}c.jd++}function xb(b,a){return(b=b.Bb.get((0===a.length?b.Qd:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Na.size)t(b);else for(const a of b.H)if(!a.I&&!a.O()){t(b);break}}function Rb(b,a,c,d){l(b,"trigger",{type:a,tags:c,aiid:d})}function Eb(b){b.Uc||(b.Uc=!0,Promise.resolve().then(()=>Sb(b)))}
function Sb(b){const a={};for(const [c,d]of b.na)a[c]=d.map(e=>e.eb());l(b,"fxstate",{fxstate:a});b.Uc=!1}
async function Gb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,n=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await tb(b,d,e,f,h,g)}catch(D){console.error("[Construct] Audio: error loading audio state: ",D);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.Va[0]=f[0],b.Va[1]=f[1],b.Va[2]=f[2],f=d.orient,b.Ua[0]=f[0],b.Ua[1]=f[1],b.Ua[2]=f[2],e.setPosition(...b.Va),e.setOrientation(...b.Ua),b.ua[0]=d.cia,b.ua[1]=d.coa,b.ua[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.sa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),vb(b,d));c.Play(k,n,p,0);a.isPlaying||c.ib();c.Fc(a)}}}function Kb(b){console.error("[Audio] Offline rendering error: ",b)}
self.cb=class extends self.Hb{constructor(b){super(b,"audio");this.Oa=this.g=null;this.Tb=this.Rc=!1;this.Aa=()=>{if(!this.Rc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Tb&&(this.Rc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Tb=!1)}};this.ma=[];this.H=[];this.R=null;this.Qd=[];this.Sd=new Set;this.Rd=-1;this.Bb=new Map;this.Zb=1;this.xa=!1;this.ed=0;this.lc=1;this.Oc=0;this.Ud="HRTF";this.Fd="inverse";this.Vd=600;this.Td=1E4;this.Xd=1;this.aa=[0,0,0];this.fa=[0,0,-1,0,1,0];this.Ld=this.ec=!1;this.$d=this.s.we();this.na=new Map;this.Na=new Set;this.Md=this.Uc=!1;this.Zc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Zc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(Nb(this,this.Zc))};this.Qb=null;self.C3Audio_GetOutputStream=()=>{this.Qb||(this.Qb=this.g.createMediaStreamDestination(),this.Oa.connect(this.Qb));return this.Qb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>pb(this,a)],["play",a=>rb(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ca()}],["stop-all",()=>{for(const a of this.H)a.Ca()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.ib():d.Jb();S(this)}],["set-volume",
a=>{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>wb(this,a)],["set-master-volume",a=>{this.Zb=a.vol;this.Oa.gain.value=this.Zb}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Tb(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.s.Kb(this.xa);for(const c of this.H)c.Ob()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.zc(a)}],["set-playback-rate",a=>yb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),vb(d,a)}],["seek",a=>zb(this,a)],["preload",a=>Ab(this,a)],["unload",a=>Bb(this,a)],["unload-all",()=>{for(const a of this.ma)a.j();this.ma.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.Ac(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>Cb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.na.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);Eb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.na.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.na.delete(a);Db(this,a)}}],["tick",a=>{this.lc=a.timeScale;this.Oc=a.gameTime;this.Rd=a.tickCount;if(0!==this.ed)for(var c of this.H)c.Ea();!(c=a.listenerPos)||this.aa[0]===c[0]&&this.aa[1]===c[1]&&this.aa[2]===c[2]||(this.aa[0]=c[0],this.aa[1]=c[1],this.aa[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.fa[0]!==
c[0]||this.fa[1]!==c[1]||this.fa[2]!==c[2]||this.fa[3]!==c[3]||this.fa[4]!==c[4]||this.fa[5]!==c[5])){for(let d=0;6>d;++d)this.fa[d]=c[d];this.g.listener.setOrientation(...this.fa)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.sa===a&&ub(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>Fb(this,a)],["offline-render-audio",a=>Ib(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ha(){return this.Oa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ha()}Ib(){return this.xa}ea(b){this.s.ea(b)}ja(b){this.s.ja(b)}Da(){for(var b of this.Na)b.Da();
b=this.g.currentTime;for(var a of this.H)a.Da(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.eb());l(this,"state",{tickCount:this.Rd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Na].map(c=>({tag:c.cd,index:c.Nd,peak:c.Wa,rms:c.Wd,binCount:c.l.frequencyBinCount,freqBins:c.Kd}))});0===a.length&&0===this.Na.size&&ba(this)}static Be(b){return b*ob}static pd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static ze(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.La.bb(self.cb);"use strict";function Lb(b){b.Xb||(b.Xb=b.Ec());return b.Xb}self.ld=class{constructor(b,a,c,d,e){this.u=b;this.bf=a;this.Ia=c;this.T=d;this.Ze=e;this.Jc="";this.Xb=null}j(){this.Xb=this.u=null}Ec(){}V(){return this.u.V()}tc(){return this.bf}fb(){return this.Ia}sc(){return this.T}Ba(){return this.Ze}ia(){}};"use strict";
self.pe=class extends self.ld{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Jc="html5";this.M=new Audio;this.M.crossOrigin="anonymous";this.M.autoplay=!1;this.M.preload="auto";this.vb=this.wb=null;this.M.addEventListener("canplaythrough",()=>!0);this.Ab=this.V().createGain();this.yb=null;this.M.addEventListener("canplay",()=>{this.wb&&(this.wb(),this.vb=this.wb=null);!this.yb&&this.M&&(this.yb=this.V().createMediaElementSource(this.M),this.yb.connect(this.Ab))});this.onended=null;this.M.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.M.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ia}' error: `,f);this.vb&&(this.vb(f),this.vb=this.wb=null)})}j(){Qb(this.u,this);this.Ab.disconnect();this.Ab=null;this.yb.disconnect();this.yb=null;this.M&&!this.M.paused&&this.M.pause();this.M=this.onended=null;super.j()}Ec(){return new Promise((b,a)=>{this.wb=b;this.vb=a;this.M.src=this.Ia})}W(){return this.M}ia(){return this.M.duration}};"use strict";
async function Ub(b){if(b.Fa)return b.Fa;var a=b.u.s;if("cordova"===a.A&&a.rd(b.Ia)&&a.Vb)b.Fa=await a.Gb(b.Ia);else{a=await fetch(b.Ia);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Vb(b){if(b.la)return b.la;b.la=await Pb(b.u,b.Fa,b.af);b.Fa=null}
self.re=class extends self.ld{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Jc="webaudio";this.la=this.Fa=null;this.af=!!f}j(){Qb(this.u,this);this.la=this.Fa=null;super.j()}async Ec(){try{await Ub(this),await Vb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ia}': `,b)}}ia(){return this.la?this.la.duration:0}};"use strict";let Wb=0;
function P(b,a){a=!!a;b.sb!==a&&(b.sb=a,b.sb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Ud,b.F.distanceModel=b.u.Fd,b.F.refDistance=b.u.Vd,b.F.maxDistance=b.u.Td,b.F.rolloffFactor=b.u.Xd),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ha())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ha())))}
function Q(b,a){a=!!a;b.Wb!==a&&(b.Wb=a,b.Wb?(P(b,!1),b.ga=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ga),b.ga.connect(b.ha())):(b.ga.disconnect(),b.ga=null,b.G.disconnect(),b.G.connect(b.ha())))}function vb(b,a){b.Wb&&b.bd!==a&&(b.ga.pan.value=a,b.bd=a)}function T(b,a){b.Ja=a;b.G.gain.cancelScheduledValues(0);b.Qa=-1;b.G.gain.value=b.uc()}function Tb(b,a){a=!!a;b.Ra!==a&&(b.Ra=a,b.Ob())}
function ub(b,a,c,d,e){if(b.sb){var f=b.Va,g=b.Ua,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Wc?b.u.Oc:performance.now()/1E3}
self.md=class{constructor(b,a,c){this.u=b;this.P=a;this.qa=c;this.Pb=Wb++;this.G=this.V().createGain();this.G.connect(this.ha());this.F=null;this.sb=!1;this.Va=[0,0,0];this.Ua=[0,0,0];this.ua=[0,0,0];this.ga=null;this.Wb=!1;this.bd=0;this.I=!0;this.Y=this.va=this.K=!1;this.Ja=1;this.Ra=!1;this.oa=1;b=this.u.ed;this.Wc=1===b&&!this.Ba()||2===b;this.Qa=this.sa=-1;this.Zd=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.ga&&(this.ga.disconnect(),this.ga=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ha(){return Nb(this.u,0<this.qa.length?this.qa[0]:"")}tc(){return this.P.tc()}fb(){return this.P.fb()}sc(){return this.P.sc()}Ba(){return this.P.Ba()}O(){}pc(){}IsPlaying(){return!this.I&&!this.K&&!this.O()}Ka(){}ia(){return this.P.ia()}Play(){}Ca(){}ib(){}Jb(){}Da(b){-1!==this.Qa&&b>=this.Qa&&(this.Qa=-1,this.Zd&&this.Ca(),Rb(this.u,"fade-ended",this.qa,this.Pb))}uc(){const b=this.Ja;return isFinite(b)?b:0}Ib(){return this.u.Ib()}Ob(){}zc(){}Ea(){}yc(){}Ac(){}vc(){}eb(){var b=
this.Pb,a=this.qa,c=this.ia(),d=-1===this.Qa?this.Ja:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Va,orient:this.Ua,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.sa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ka(),playbackRate:this.oa,uid:this.sa,bufferOriginalUrl:this.tc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.Ra,resumePosition:this.vc(),pan:f,stereoPan:this.ga?
this.bd:null}}Fc(b){var a=b.playbackRate;this.oa!==a&&(this.oa=a,this.Ea());Tb(this,b.isMuted)}};"use strict";
self.qe=class extends self.md{constructor(b,a,c){super(b,a,c);this.P.Ab.connect(this.G);this.P.onended=()=>this.Gc()}j(){this.Ca();this.P.Ab.disconnect();super.j()}W(){return this.P.W()}Gc(){this.I=!0;this.sa=-1;Rb(this.u,"ended",this.qa,this.Pb)}O(){return this.W().ended}pc(){return this.I?!0:this.O()}Ka(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.ia()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.fb()}' to position '${c}': `,e)}this.u.ea(d);this.K=this.I=!1;this.Y=b;this.oa=1}Ca(){const b=this.W();b.paused||b.pause();this.u.ja(b);this.I=!0;this.K=!1;this.sa=-1}ib(){if(!(this.K||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.ja(b);this.K=!0}}Jb(){!this.K||this.I||this.O()||(this.u.ea(this.W()),this.K=!1)}Ob(){this.W().muted=this.Ra||this.Ib()}zc(b){b=!!b;this.Y!==b&&(this.Y=
b,this.W().loop=b)}Ea(){let b=this.oa;this.Wc&&(b*=this.u.lc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}yc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}vc(){return this.Ka()}Ac(b){b?this.IsPlaying()?(this.W().pause(),this.va=!0):this.va=!1:this.va&&(this.u.ea(this.W()),this.va=!1)}};"use strict";
function V(b){b.o&&(b.o.onended=null,b.o.disconnect(),b.o.buffer=null);b.o=null;b.lb=null}
self.se=class extends self.md{constructor(b,a,c){super(b,a,c);this.o=null;this.bc=d=>this.Gc(d);this.Qc=!0;this.lb=null;this.S=this.dc=this.fc=0;this.$c=1}j(){this.Ca();V(this);this.bc=null;super.j()}Gc(b){this.K||this.va||b.target!==this.lb||(this.I=this.Qc=!0,this.sa=-1,V(this),Rb(this.u,"ended",this.qa,this.Pb))}O(){return!this.I&&this.o&&this.o.loop||this.K?!1:this.Qc}pc(){return!this.o||this.I?!0:this.O()}Ka(){let b;b=this.K?this.S:this.dc+(U(this)-this.fc)*this.oa;this.Y||(b=Math.min(b,this.ia()));
return b}Play(b,a,c,d){this.$c=1;T(this,a);V(this);this.o=this.V().createBufferSource();this.o.buffer=this.P.la;this.o.connect(this.G);this.lb=this.o;this.o.onended=this.bc;this.o.loop=b;this.o.start(d,c);this.K=this.I=this.Qc=!1;this.Y=b;this.oa=1;this.fc=U(this);this.dc=c}Ca(){if(this.o)try{this.o.stop(0)}catch(b){}this.I=!0;this.K=!1;this.sa=-1}ib(){this.K||this.I||this.O()||(this.S=this.Ka(),this.Y&&(this.S%=this.ia()),this.K=!0,this.o.stop(0))}Jb(){!this.K||this.I||this.O()||(V(this),this.o=
this.V().createBufferSource(),this.o.buffer=this.P.la,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.bc,this.o.loop=this.Y,T(this,this.Ja),this.Ea(),this.o.start(0,this.S),this.fc=U(this),this.dc=this.S,this.K=!1)}uc(){return super.uc()*this.$c}Ob(){this.$c=this.Ra||this.Ib()?0:1;T(this,this.Ja)}zc(b){b=!!b;this.Y!==b&&(this.Y=b,this.o&&(this.o.loop=b))}Ea(){let b=this.oa;this.Wc&&(b*=this.u.lc);this.o&&(this.o.playbackRate.value=b)}yc(b){this.I||this.O()||(this.K?this.S=b:(this.ib(),this.S=
b,this.Jb()))}vc(){return this.S}Ac(b){b?this.IsPlaying()?(this.va=!0,this.S=this.Ka(),this.Y&&(this.S%=this.ia()),this.o.stop(0)):this.va=!1:this.va&&(V(this),this.o=this.V().createBufferSource(),this.o.buffer=this.P.la,this.o.connect(this.G),this.lb=this.o,this.o.onended=this.bc,this.o.loop=this.Y,T(this,this.Ja),this.Ea(),this.o.start(0,this.S),this.fc=U(this),this.dc=this.S,this.va=!1)}Fc(b){super.Fc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Nd=-1;this.T=this.cd="";this.m=null}j(){this.g=null}N(){}U(){}eb(){return{type:this.T,tag:this.cd,params:this.m}}}
self.ie=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.m=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.m[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.m[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.m[4]=a,X(this,this.D.gain,a,c,d)}}};
self.ge=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.m=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.xb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.qb=W(this);this.qb.gain.value=c;this.v.connect(this.xb);this.v.connect(this.h);this.xb.connect(this.i);this.xb.connect(this.X);this.X.connect(this.qb);this.qb.connect(this.xb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.xb.disconnect();
this.X.disconnect();this.qb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.cb.pd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.m[1]=e(a);X(this,this.qb.gain,e(a),c,d);break;case 5:this.m[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.fe=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.m=[c,d];this.Ed=this.Dd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.pb=this.g.createConvolver();this.pb.normalize=c;this.pb.buffer=a;this.v.connect(this.pb);this.v.connect(this.h);this.pb.connect(this.i)}j(){this.v.disconnect();this.pb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}eb(){const b=super.eb();b.bufferOriginalUrl=this.Dd;b.bufferUrl="";b.bufferType=this.Ed;return b}};
self.je=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.m=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.rb=W(this);this.rb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.L=W(this);this.L.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.rb);this.rb.connect(this.X);this.B.connect(this.L);
this.L.connect(this.X.delayTime);this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.X.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();this.rb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.m[1]=a/1E3;X(this,this.L.gain,a/1E3,
c,d);break;case 7:this.m[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.m[3]=a/100,X(this,this.rb.gain,a/100,c,d)}}};
self.le=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.m=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.L=W(this);this.L.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.B.connect(this.L);this.L.connect(this.D.frequency);
this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.D.disconnect();this.B.disconnect();this.L.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.m[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.m[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.m[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.m[3]=a;X(this,this.L.gain,a,c,d);break;case 7:this.m[4]=a,X(this,this.B.frequency,a,c,d)}}};self.ke=class extends Y{constructor(b,a){super(b);this.T="gain";this.m=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.cb.pd;switch(b){case 4:this.m[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.ne=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.m=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.m[0]=a,X(this,this.l.pan,a,c,d)}}};
self.oe=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.m=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.L=W(this);this.L.gain.value=c/2;this.B.connect(this.L);this.L.connect(this.l.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.L.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.L.gain,a/2,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.me=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.m=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Db=W(this);this.Db.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.Db.gain);this.B.start(0);this.v.connect(this.Db);this.v.connect(this.h);this.Db.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.Db.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.m[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.m[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.he=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.m=[a,c,d,e,f];this.v=W(this);this.ic=W(this);this.hc=W(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.mc=this.g.createWaveShaper();this.Kc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Kc[32768+e]=f,this.Kc[32768-
e-1]=-f;this.mc.curve=this.Kc;this.v.connect(this.ic);this.v.connect(this.h);this.ic.connect(this.mc);this.mc.connect(this.hc);this.hc.connect(this.i)}j(){this.v.disconnect();this.ic.disconnect();this.mc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.m[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.ee=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.m=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.de=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.m=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Kd=new Float32Array(this.l.frequencyBinCount);this.Yd=new Uint8Array(a);this.Wd=this.Wa=0;b=this.u;b.Na.add(this);S(b)}j(){this.u.Na.delete(this);this.l.disconnect();super.j()}Da(){this.l.getFloatFrequencyData(this.Kd);this.l.getByteTimeDomainData(this.Yd);const b=this.l.fftSize;let a=this.Wa=0;for(var c=0;c<b;++c){let d=(this.Yd[c]-
128)/128;0>d&&(d=-d);this.Wa<d&&(this.Wa=d);a+=d*d}c=self.cb.ze;this.Wa=c(this.Wa);this.Wd=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Xb(b,a){b.Vc=a.isInWorker;a=document.createElement("video");b.kc=!!a.requestVideoFrameCallback&&!b.s.wc();const c=!!self.createImageBitmap;b.Cb=b.Vc||c;return{postImageBitmaps:b.Cb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Yb(b,a){if(!b.Lc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Yb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Lc.has(a)||u(b,"playback-event",c,{type:d})}
self.La.bb(class extends self.od{constructor(b){super(b,"video");this.Cb=this.kc=this.Vc=this.mb=!1;this.ac=this.df=0;this.Lc=new WeakSet;q(this,"init",a=>Xb(this,a));v(this,"play",a=>{this.ea(a)});v(this,"pause",a=>{this.ja(a);a.pause()});v(this,"set-source",(a,c)=>{a.src=c.src;a.load()});v(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});v(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});v(this,"set-looping",(a,c)=>{a.loop=c.isLooping});v(this,"set-muted",(a,c)=>{a.muted=c.isMuted});v(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>w(this,a)}ea(b){this.s.ea(b);this.Cb&&this.kc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Yb(this,b)))}ja(b){this.s.ja(b);this.Cb&&this.kc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}qc(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ea(c);this.ac++;t(this);return c}Lb(){}qd(b){this.ja(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.ac=Math.max(this.ac-1,0);0===this.ac&&ba(this);this.Lc.add(b)}Da(){const b={},a={sequenceNumber:this.df++,videoData:b},c=[],d=[];for(const [e,f]of this.Pa.entries()){const g=f.Sb,h={currentTime:g.currentTime,playbackRate:g.playbackRate,duration:g.duration,videoWidth:g.videoWidth,
videoHeight:g.videoHeight};if(this.Cb)if(this.kc){const k=g.c3_imageBitmap;g.c3_imageBitmap=null;(h.imageBitmap=k)&&c.push(k)}else d.push(createImageBitmap(g).then(k=>{h.imageBitmap=k;c.push(k)}).catch(()=>{h.imageBitmap=null}));b[e.toString()]=h}Promise.all(d).then(()=>{this.Vc?l(this,"state",a,!1,c):m(this,"state",a)})}});
